language: rust

sudo: false

# Necessary for `travis-cargo coveralls --no-sudo`.
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - stable
  - beta
  - nightly

env:
  - CRATE=rmp
  - CRATE=rmp-serialize
  - CRATE=rmp-serde FEATURES=serde_macros

# Load travis-cargo.
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - (cd $CRATE && cargo test --features=$FEATURES)

# Measure code coverage and upload to coveralls.io.
after_success:
  - (cd $CRATE && travis-cargo coveralls --no-sudo)
