[package]
name = "rmpv"
version = "0.1.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Value variant for RMP"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://docs.rs/rmpv"
readme = "../README.md"
keywords = ["msgpack", "MessagePack", "serialization"]

[features]
with-serde = ["serde"]

[dependencies]
rmp = "0.8"
serde = { version = "^0.9", optional = true }

[dev-dependencies]
quickcheck = "0.3"
