[package]
name = "rmp-serde-tests"
version = "0.0.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
publish = false

[dependencies]
rmp = "0.8"
rmp-serde = { path = "../rmp-serde", version = "*" }
serde = "0.9"
serde_derive = "0.9"
